global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

  # MemoryBank instances (dynamically discovered via Docker labels)
  - job_name: 'memorybank-instances'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only scrape containers with the label "prometheus.scrape=true"
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: true
        action: keep
      
      # Use the container name as the instance label
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      
      # Extract tenant ID from container name
      - source_labels: [__meta_docker_container_name]
        regex: 'memorybank-(.+)'
        target_label: tenant_id
      
      # Use custom port if specified
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __address__
        regex: (.+)
        replacement: ${1}
      
      # Default to port 8000 if no custom port
      - source_labels: [__address__]
        regex: '([^:]+)(?::\d+)?'
        target_label: __address__
        replacement: '${1}:8000'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['dockerd-exporter:9323']